example/rails_app/config/routes.rb
Rails.application.routes.draw do
  resources :samples
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

example/rails_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

example/rails_app/app/models/sample.rb
class Sample < ApplicationRecord
end

example/rails_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

example/rails_app/app/controllers/samples_controller.rb
class SamplesController < ApplicationController
  before_action :set_sample, only: %i[ show edit update destroy ]

  # GET /samples or /samples.json
  def index
    x = 123
    y = x * 3
    p "Hello World!"
    @samples = Sample.all
    render json: { x: x, y: y }
  end

  # GET /samples/1 or /samples/1.json
  def show
  end

  # GET /samples/new
  def new
    @sample = Sample.new
  end

  # GET /samples/1/edit
  def edit
  end

  # POST /samples or /samples.json
  def create
    @sample = Sample.new(sample_params)

    respond_to do |format|
      if @sample.save
        format.html { redirect_to @sample, notice: "Sample was successfully created." }
        format.json { render :show, status: :created, location: @sample }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @sample.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /samples/1 or /samples/1.json
  def update
    respond_to do |format|
      if @sample.update(sample_params)
        format.html { redirect_to @sample, notice: "Sample was successfully updated." }
        format.json { render :show, status: :ok, location: @sample }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @sample.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /samples/1 or /samples/1.json
  def destroy
    @sample.destroy!

    respond_to do |format|
      format.html { redirect_to samples_path, status: :see_other, notice: "Sample was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sample
      @sample = Sample.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def sample_params
      params.require(:sample).permit(:name)
    end
end

example/rails_app/app/helpers/application_helper.rb
module ApplicationHelper
end

example/rails_app/app/helpers/samples_helper.rb
module SamplesHelper
end

example/rails_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Rails App" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

example/rails_app/app/views/samples/_form.html.erb
<%= form_with(model: sample) do |form| %>
  <% if sample.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(sample.errors.count, "error") %> prohibited this sample from being saved:</h2>

      <ul>
        <% sample.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

example/rails_app/app/views/samples/_sample.html.erb
<div id="<%= dom_id sample %>">
  <p>
    <strong>Name:</strong>
    <%= sample.name %>
  </p>

</div>

example/rails_app/app/views/samples/edit.html.erb
<% content_for :title, "Editing sample" %>

<h1>Editing sample</h1>

<%= render "form", sample: @sample %>

<br>

<div>
  <%= link_to "Show this sample", @sample %> |
  <%= link_to "Back to samples", samples_path %>
</div>

example/rails_app/app/views/samples/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Samples" %>

<h1>Samples</h1>

<div id="samples">
  <% @samples.each do |sample| %>
    <%= render sample %>
    <p>
      <%= link_to "Show this sample", sample %>
    </p>
  <% end %>
</div>

<%= link_to "New sample", new_sample_path %>

example/rails_app/app/views/samples/new.html.erb
<% content_for :title, "New sample" %>

<h1>New sample</h1>

<%= render "form", sample: @sample %>

<br>

<div>
  <%= link_to "Back to samples", samples_path %>
</div>

example/rails_app/app/views/samples/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @sample %>

<div>
  <%= link_to "Edit this sample", edit_sample_path(@sample) %> |
  <%= link_to "Back to samples", samples_path %>

  <%= button_to "Destroy this sample", @sample, method: :delete %>
</div>